= riemann-ruby-experiments
Chris Riddoch <riddochc@gmail.com>
:language: ruby
:homepage: https://syntacticsugar.org/projects/riemann-ruby-experiments
:revnumber: 0.0.1
:revdate: 2016-05-19

== Description

A Riemann client for ruby

Just another client, to experiment with.

== Requirements

* A riemann server to talk to

== Installation

gem install riemann-ruby-experiments

== Use

Include the following line in your Gemfile:

  gem 'riemann-ruby-experiments'

Then, you can use it like this:

  c = Riemann::Experiment::Client.new(host: Socket.gethostname, service: "A new riemann logger!")
  e = {time: Time.now.to_i,
       description: "An event of some sort"}
  r = c.send_event(e)

Or:

  c = Riemann::Experiment::Client.new(:host => :default, :service => :default)
  e = {description: "An event of some sort", metric: 42.73, a: 1, b: 2}
  r = c.send_event(e)

== Contributing

Pull requests welcome.

== Contributors

* Chris Riddoch

== History

=== Version 0.0.1

* Initial release, yay!

== License

Copyright © 2016 Chris Riddoch

See LICENSE for license details

