= riemann-ruby-experiments
Chris Riddoch <riddochc@gmail.com>
:language: ruby
:homepage: https://syntacticsugar.org/projects/riemann-ruby-experiments
:revnumber: 0.0.2
:revdate: 2016-05-29

== Description

A Riemann client for ruby

Just another client, to experiment with.

== Requirements

* A riemann server to talk to

== Installation

gem install riemann-ruby-experiments

== Use

Include the following line in your Gemfile:

  gem 'riemann-ruby-experiments'

Then, you can use it like this:

  c = Riemann::Experiment::Client.new(server: "localhost:5555", service: "A new riemann logger!")
  h = {time: Time.now.to_i,
       description: "An event of some sort",
       metric: 42.15,
       anotherkey: "anothervalue"}
  c.add_event(h)
  
  h2 = {time: Time.now.to_i, description: "Another event", metric: 73}
  c.add_event(h2)
  
  response = c.send_message(:ok => "ok")

  if response.ok == 'ok'
    # acknowledged by server...
  end

== Contributing

Pull requests welcome.

== Contributors

* Chris Riddoch

== History

=== Version 0.0.1

* Initial release, yay!

== License

Copyright © 2016 Chris Riddoch

See LICENSE for license details

